-- MySQL Script generated by MySQL Workbench
-- Mon Oct  5 06:15:51 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Country` (
  `COUNTRY_ID` VARCHAR(45) NOT NULL,
  `COUNTRY_NAME` VARCHAR(45) NULL,
  `TOTAL_DEATHS` VARCHAR(45) NULL,
  `PRESENT_POPULATION` VARCHAR(45) NULL,
  PRIMARY KEY (`COUNTRY_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Provice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Provice` (
  `PROVINCE_ID` VARCHAR(45) NOT NULL,
  `PROVINCE_NAME` VARCHAR(45) NULL,
  `PROVINCE_PERCENTAGE_AFFECTED` VARCHAR(45) NULL,
  `PROVINCE_INFO` VARCHAR(45) NULL,
  `PROVINCE_PERCENTAGE_RECOVERED` VARCHAR(45) NULL,
  `Country data Covid-19 Cases_C_NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Country data Covid-19 Cases_C_NAME`, `PROVINCE_ID`),
  CONSTRAINT `fk_Provice data Covid-19_Country data Covid-19 Cases1`
    FOREIGN KEY (`Country data Covid-19 Cases_C_NAME`)
    REFERENCES `mydb`.`Country` (`COUNTRY_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`City`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`City` (
  `CITY_NAME` VARCHAR(10) NOT NULL,
  `CITY_PROVINCE` VARCHAR(45) NULL,
  `CITY_PERCENTAGE_AFFECTED` VARCHAR(45) NULL,
  `CITY_PERCENTAGE_RECOVERED` VARCHAR(45) NULL,
  `CITY_INFO` VARCHAR(45) NULL,
  `Provicies Data for Covid-19_P_NAME` INT NOT NULL,
  PRIMARY KEY (`CITY_NAME`, `Provicies Data for Covid-19_P_NAME`),
--   INDEX `fk_City Data for Covid-19_Provicies Data for Covid-191_idx` (`Provicies Data for Covid-19_P_NAME` ASC) VISIBLE,
  CONSTRAINT `fk_City Data for Covid-19_Provicies Data for Covid-191`
    FOREIGN KEY (`Provicies Data for Covid-19_P_NAME`)
    REFERENCES `mydb`.`Provice` (`PROVINCE_NAME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`COVID-19 Financial Assistance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`COVID-19 Financial Assistance` (
  `FA_ID` INT NOT NULL,
  `FA_ELIGIBILITY` VARCHAR(45) NULL,
  `FA__INFO` VARCHAR(45) NULL,
  `City Data for Covid-19_C_NAME` INT NOT NULL,
  PRIMARY KEY (`FA_ID`),
 --  INDEX `fk_Covid-19 Financial Assistance_City Data for Covid-191_idx` (`City Data for Covid-19_C_NAME` ASC) VISIBLE,
  CONSTRAINT `fk_Covid-19 Financial Assistance_City Data for Covid-191`
    FOREIGN KEY (`City Data for Covid-19_C_NAME`)
    REFERENCES `mydb`.`City` (`CITY_NAME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`COVID-19 Center`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`COVID-19 Center` (
  `CC_ID` INT NULL,
  `CC_ADDRESS` VARCHAR(45) NULL,
  `CC_AVAILABLE_BEDS` VARCHAR(45) NULL,
  `CC_OCCUPIES_BEDS` VARCHAR(45) NULL,
  `CC_STATUS` VARCHAR(45) NULL,
  `City Affected by Covid-19_C_NAME` VARCHAR(10) NOT NULL,
  `CC_INFO` VARCHAR(45) NULL,
  `City Affected by Covid-19_Provicies Data for Covid-19_P_NAME` INT NOT NULL,
  PRIMARY KEY (`CC_ID`, `City Affected by Covid-19_C_NAME`, `City Affected by Covid-19_Provicies Data for Covid-19_P_NAME`),
 --  INDEX `fk_Covid-19 Center_City Affected by Covid-191_idx` (`City Affected by Covid-19_C_NAME` ASC, `City Affected by Covid-19_Provicies Data for Covid-19_P_NAME` ASC) VISIBLE,
  CONSTRAINT `fk_Covid-19 Center_City Affected by Covid-191`
    FOREIGN KEY (`City Affected by Covid-19_C_NAME` , `City Affected by Covid-19_Provicies Data for Covid-19_P_NAME`)
    REFERENCES `mydb`.`City` (`CITY_NAME` , `Provicies Data for Covid-19_P_NAME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Hospital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Hospital` (
  `H_ID` INT NOT NULL,
  `H_NAME` VARCHAR(45) NULL,
  `H_ADDRESS` VARCHAR(45) NULL,
  `H_PHONE_NUMBER` VARCHAR(45) NULL,
  `H_INFO` VARCHAR(45) NULL,
  PRIMARY KEY (`H_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`COVID-19 Patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`COVID-19 Patient` (
  `CP_ID` INT NOT NULL,
  `CP_NAME` VARCHAR(45) NULL,
  `CP_AGE` INT NULL,
  `CP_GENDER` VARCHAR(15) NULL,
  `DATE_OF_BIRTH` VARCHAR(15) NULL,
  `CP_PHONE_NUMBER` INT NULL,
  `CP_ADDRESS` VARCHAR(45) NULL,
  `Covid-19 Patient_CP_ID` INT NOT NULL,
  `Building_B_ID` INT NOT NULL,
  `Building_Hospital_H_ID` INT NOT NULL,
  `Covid-19 Financial Assistance_FA_ID` INT NOT NULL,
  `Covid-19 Centers_CC_ID` INT NOT NULL,
  `Hospital_H_ID` INT NOT NULL,
  PRIMARY KEY (`CP_ID`, `Covid-19 Patient_CP_ID`, `Building_B_ID`, `Building_Hospital_H_ID`, `Covid-19 Financial Assistance_FA_ID`, `Covid-19 Centers_CC_ID`, `Hospital_H_ID`),
  -- INDEX `fk_Covid-19 Patient_Covid-19 Financial Assistance1_idx` (`Covid-19 Financial Assistance_FA_ID` ASC) VISIBLE,
 --  INDEX `fk_Covid-19 Patient_Covid-19 Centers1_idx` (`Covid-19 Centers_CC_ID` ASC) VISIBLE,
  -- INDEX `fk_COVID-19 Patient_Hospital1_idx` (`Hospital_H_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Covid-19 Patient_Covid-19 Financial Assistance1`
    FOREIGN KEY (`Covid-19 Financial Assistance_FA_ID`)
    REFERENCES `mydb`.`COVID-19 Financial Assistance` (`FA_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Covid-19 Patient_Covid-19 Centers1`
    FOREIGN KEY (`Covid-19 Centers_CC_ID`)
    REFERENCES `mydb`.`COVID-19 Center` (`CC_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COVID-19 Patient_Hospital1`
    FOREIGN KEY (`Hospital_H_ID`)
    REFERENCES `mydb`.`Hospital` (`H_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Medical Record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Medical Record` (
  `DATE_OF_EXAMINATION` VARCHAR(45) NULL,
  `CONDITION` VARCHAR(45) NULL,
  `COVID-19 Patient_CP_ID` INT NOT NULL,
  PRIMARY KEY (`COVID-19 Patient_CP_ID`),
  CONSTRAINT `fk_Medical Record_COVID-19 Patient1`
    FOREIGN KEY (`COVID-19 Patient_CP_ID`)
    REFERENCES `mydb`.`COVID-19 Patient` (`CP_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bill` (
  `B_ID` INT NOT NULL,
  `B_DATE` VARCHAR(45) NULL,
  `B_PURPOSE` VARCHAR(45) NULL,
  `B_AMOUNT` VARCHAR(45) NULL,
  `Covid-19 Patient_CP_ID` INT NOT NULL,
  `Covid-19 Patient_Covid-19 Patient_CP_ID` INT NOT NULL,
  `Hospital_H_ID` INT NOT NULL,
  PRIMARY KEY (`B_ID`, `Covid-19 Patient_CP_ID`, `Covid-19 Patient_Covid-19 Patient_CP_ID`, `Hospital_H_ID`),
  -- INDEX `fk_Bill_Covid-19 Patient1_idx` (`Covid-19 Patient_CP_ID` ASC, `Covid-19 Patient_Covid-19 Patient_CP_ID` ASC) VISIBLE,
 --  INDEX `fk_Bill_Hospital1_idx` (`Hospital_H_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Bill_Covid-19 Patient1`
    FOREIGN KEY (`Covid-19 Patient_CP_ID` , `Covid-19 Patient_Covid-19 Patient_CP_ID`)
    REFERENCES `mydb`.`COVID-19 Patient` (`CP_ID` , `Covid-19 Patient_CP_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bill_Hospital1`
    FOREIGN KEY (`Hospital_H_ID`)
    REFERENCES `mydb`.`Hospital` (`H_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Owner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Owner` (
  `OWNER_NAME` INT NOT NULL,
  `OWNER_ID` INT NOT NULL,
  `OWNER_INFO` VARCHAR(45) NULL,
  PRIMARY KEY (`OWNER_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Building`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Building` (
  `B_ID` INT NOT NULL,
  `B_NAME` VARCHAR(45) NULL,
  `B_ADDRESS` VARCHAR(45) NULL,
  `Hospital_H_ID` INT NOT NULL,
  `Owner_OWNER_ID` INT NOT NULL,
  PRIMARY KEY (`B_ID`, `Hospital_H_ID`),
 --  INDEX `fk_Building_Hospital1_idx` (`Hospital_H_ID` ASC) VISIBLE,
--   INDEX `fk_Building_Owner1_idx` (`Owner_OWNER_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Building_Hospital1`
    FOREIGN KEY (`Hospital_H_ID`)
    REFERENCES `mydb`.`Hospital` (`H_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Building_Owner1`
    FOREIGN KEY (`Owner_OWNER_ID`)
    REFERENCES `mydb`.`Owner` (`OWNER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Doctor` (
  `D_ID` INT NOT NULL,
  `D_NAME` VARCHAR(45) NULL,
  `D_DEPARTMENT` VARCHAR(45) NULL,
  `D_SALARY` VARCHAR(45) NULL,
  `D_GENDER` VARCHAR(45) NULL,
  `D_INFO` VARCHAR(45) NULL,
  `D_ADDRESS` VARCHAR(45) NULL,
  PRIMARY KEY (`D_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Appointment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Appointment` (
  `A_ID` INT NOT NULL,
  `A_TIME` VARCHAR(45) NULL,
  `A_DATE` VARCHAR(45) NULL,
  `A_PURPOSE` VARCHAR(45) NULL,
  `Covid-19 Patient_CP_ID` INT NOT NULL,
  `Covid-19 Patient_Covid-19 Patient_CP_ID` INT NOT NULL,
  `Doctor_D_ID` INT NOT NULL,
  `Building_B_ID` INT NOT NULL,
  `Building_Hospital_H_ID` INT NOT NULL,
  PRIMARY KEY (`A_ID`, `Covid-19 Patient_CP_ID`, `Covid-19 Patient_Covid-19 Patient_CP_ID`, `Doctor_D_ID`, `Building_B_ID`, `Building_Hospital_H_ID`),
  -- INDEX `fk_Appointment_Covid-19 Patient1_idx` (`Covid-19 Patient_CP_ID` ASC, `Covid-19 Patient_Covid-19 Patient_CP_ID` ASC) VISIBLE,
 --  INDEX `fk_Appointment_Doctor1_idx` (`Doctor_D_ID` ASC) VISIBLE,
 --  INDEX `fk_Appointment_Building1_idx` (`Building_B_ID` ASC, `Building_Hospital_H_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Appointment_Covid-19 Patient1`
    FOREIGN KEY (`Covid-19 Patient_CP_ID` , `Covid-19 Patient_Covid-19 Patient_CP_ID`)
    REFERENCES `mydb`.`COVID-19 Patient` (`CP_ID` , `Covid-19 Patient_CP_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Appointment_Doctor1`
    FOREIGN KEY (`Doctor_D_ID`)
    REFERENCES `mydb`.`Doctor` (`D_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Appointment_Building1`
    FOREIGN KEY (`Building_B_ID` , `Building_Hospital_H_ID`)
    REFERENCES `mydb`.`Building` (`B_ID` , `Hospital_H_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Specialty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Specialty` (
  `S_ID` INT NOT NULL,
  `S_NAME` VARCHAR(45) NULL,
  `S_INFO` VARCHAR(45) NULL,
  `Doctor_D_ID` INT NOT NULL,
  PRIMARY KEY (`S_ID`),
--   INDEX `fk_Speciality_Doctor1_idx` (`Doctor_D_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Speciality_Doctor1`
    FOREIGN KEY (`Doctor_D_ID`)
    REFERENCES `mydb`.`Doctor` (`D_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Emergency Services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Emergency Services` (
  `ES_ID` INT NOT NULL,
  `ES_NAME` VARCHAR(45) NULL,
  `ES_COMMUNITY` VARCHAR(45) NULL,
  PRIMARY KEY (`ES_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Patient_Emergency Services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Patient_Emergency Services` (
  `Covid-19 Patient_CP_ID` INT NOT NULL,
  `Covid-19 Patient_Covid-19 Patient_CP_ID` INT NOT NULL,
  `Emergency Services_ES_ID` INT NOT NULL,
  PRIMARY KEY (`Covid-19 Patient_CP_ID`, `Covid-19 Patient_Covid-19 Patient_CP_ID`, `Emergency Services_ES_ID`),
--   INDEX `fk_Covid-19 Patient_has_Emergency Services_Emergency Servic_idx` (`Emergency Services_ES_ID` ASC) VISIBLE,
 --  INDEX `fk_Covid-19 Patient_has_Emergency Services_Covid-19 Patient_idx` (`Covid-19 Patient_CP_ID` ASC, `Covid-19 Patient_Covid-19 Patient_CP_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Covid-19 Patient_has_Emergency Services_Covid-19 Patient1`
    FOREIGN KEY (`Covid-19 Patient_CP_ID` , `Covid-19 Patient_Covid-19 Patient_CP_ID`)
    REFERENCES `mydb`.`COVID-19 Patient` (`CP_ID` , `Covid-19 Patient_CP_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Covid-19 Patient_has_Emergency Services_Emergency Services1`
    FOREIGN KEY (`Emergency Services_ES_ID`)
    REFERENCES `mydb`.`Emergency Services` (`ES_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Hospital_has_Doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Hospital_has_Doctor` (
  `Hospital_H_ID` INT NOT NULL,
  `Doctor_D_ID` INT NOT NULL,
--   INDEX `fk_Hospital_has_Doctor_Doctor1_idx` (`Doctor_D_ID` ASC) VISIBLE,
 --  INDEX `fk_Hospital_has_Doctor_Hospital1_idx` (`Hospital_H_ID` ASC) VISIBLE,
  PRIMARY KEY (`Hospital_H_ID`, `Doctor_D_ID`),
  CONSTRAINT `fk_Hospital_has_Doctor_Hospital1`
    FOREIGN KEY (`Hospital_H_ID`)
    REFERENCES `mydb`.`Hospital` (`H_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hospital_has_Doctor_Doctor1`
    FOREIGN KEY (`Doctor_D_ID`)
    REFERENCES `mydb`.`Doctor` (`D_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Hospital_Speciality`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Hospital_Speciality` (
  `Hospital_H_ID` INT NOT NULL,
  `SPECIALITY_S_ID` INT NOT NULL,
  PRIMARY KEY (`Hospital_H_ID`, `SPECIALITY_S_ID`),
 --  INDEX `fk_Hospital_has_SPECIALITY_SPECIALITY1_idx` (`SPECIALITY_S_ID` ASC) VISIBLE,
  -- INDEX `fk_Hospital_has_SPECIALITY_Hospital1_idx` (`Hospital_H_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Hospital_has_SPECIALITY_Hospital1`
    FOREIGN KEY (`Hospital_H_ID`)
    REFERENCES `mydb`.`Hospital` (`H_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hospital_has_SPECIALITY_SPECIALITY1`
    FOREIGN KEY (`SPECIALITY_S_ID`)
    REFERENCES `mydb`.`Specialty` (`S_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Routes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Routes` (
  `ROUTE_ID` VARCHAR(45) NOT NULL,
  `ROUTE_NAME` INT NULL,
  `ROUTE_ADDRESS` VARCHAR(45) NULL,
  `ROUTE_STATUS` VARCHAR(45) NULL,
  `ROUTE_INFO` VARCHAR(45) NULL,
  `City Data for Covid-19_C_NAME` INT NOT NULL,
  PRIMARY KEY (`City Data for Covid-19_C_NAME`, `ROUTE_ID`),
 --  INDEX `fk_Routes Affected due to Covid-19_City Data for Covid-191_idx` (`City Data for Covid-19_C_NAME` ASC) VISIBLE,
  CONSTRAINT `fk_Routes Affected due to Covid-19_City Data for Covid-191`
    FOREIGN KEY (`City Data for Covid-19_C_NAME`)
    REFERENCES `mydb`.`City` (`CITY_NAME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`City_Emergency Services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`City_Emergency Services` (
  `City Data for Covid-19_C_NAME` INT NOT NULL,
  `City Data for Covid-19_Provicies Data for Covid-19_P_NAME` INT NOT NULL,
  `Emergency Services_ES_ID` INT NOT NULL,
  PRIMARY KEY (`City Data for Covid-19_C_NAME`, `City Data for Covid-19_Provicies Data for Covid-19_P_NAME`, `Emergency Services_ES_ID`),
 --  INDEX `fk_City Data for Covid-19_has_Emergency Services_Emergency _idx` (`Emergency Services_ES_ID` ASC) VISIBLE,
  -- INDEX `fk_City Data for Covid-19_has_Emergency Services_City Data _idx` (`City Data for Covid-19_C_NAME` ASC, `City Data for Covid-19_Provicies Data for Covid-19_P_NAME` ASC) VISIBLE,
  CONSTRAINT `fk_City Data for Covid-19_has_Emergency Services_City Data fo1`
    FOREIGN KEY (`City Data for Covid-19_C_NAME` , `City Data for Covid-19_Provicies Data for Covid-19_P_NAME`)
    REFERENCES `mydb`.`City` (`CITY_NAME` , `Provicies Data for Covid-19_P_NAME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_City Data for Covid-19_has_Emergency Services_Emergency Se1`
    FOREIGN KEY (`Emergency Services_ES_ID`)
    REFERENCES `mydb`.`Emergency Services` (`ES_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Plasma Collection Center`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Plasma Collection Center` (
  `P_ID` INT NOT NULL,
  `P_TYPE` VARCHAR(45) NULL,
  `P_HEALTH_AUTHORITY` VARCHAR(45) NULL,
  `City_CITY_NAME` VARCHAR(10) NOT NULL,
  `City_Provicies Data for Covid-19_P_NAME` INT NOT NULL,
  PRIMARY KEY (`P_ID`),
  -- INDEX `fk_Plasma Collection Center_City1_idx` (`City_CITY_NAME` ASC, `City_Provicies Data for Covid-19_P_NAME` ASC) VISIBLE,
  CONSTRAINT `fk_Plasma Collection Center_City1`
    FOREIGN KEY (`City_CITY_NAME` , `City_Provicies Data for Covid-19_P_NAME`)
    REFERENCES `mydb`.`City` (`CITY_NAME` , `Provicies Data for Covid-19_P_NAME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Address` (
  `STREET_ADDRESS` INT NULL,
  `CITY` VARCHAR(45) NULL,
  `ZIP CODE` VARCHAR(45) NULL,
  `COUNTRY` VARCHAR(45) NULL,
  `Covid-19 Patient_CP_ID` INT NOT NULL,
  `Covid-19 Patient_Building_Hospital_H_ID` INT NOT NULL,
  `Doctor_D_ID` INT NOT NULL,
  PRIMARY KEY (`Covid-19 Patient_CP_ID`, `Covid-19 Patient_Building_Hospital_H_ID`, `Doctor_D_ID`),
  -- INDEX `fk_Address_Covid-19 Patient1_idx` (`Covid-19 Patient_CP_ID` ASC) VISIBLE,
 --  INDEX `fk_Address_Doctor1_idx` (`Doctor_D_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Address_Covid-19 Patient1`
    FOREIGN KEY (`Covid-19 Patient_CP_ID`)
    REFERENCES `mydb`.`COVID-19 Patient` (`CP_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Address_Doctor1`
    FOREIGN KEY (`Doctor_D_ID`)
    REFERENCES `mydb`.`Doctor` (`D_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`External Medical Sources`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`External Medical Sources` (
  `Hospital_H_ID` INT NOT NULL,
  `TP_INSTRUMENTS` VARCHAR(45) NULL,
  `TP_SERVICES` VARCHAR(45) NULL,
  `TP_INFORMATION` VARCHAR(45) NULL,
  -- INDEX `fk_External Medical Sources_Hospital1_idx` (`Hospital_H_ID` ASC) VISIBLE,
  CONSTRAINT `fk_External Medical Sources_Hospital1`
    FOREIGN KEY (`Hospital_H_ID`)
    REFERENCES `mydb`.`Hospital` (`H_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Blood Bank`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Blood Bank` (
  `BANK_ID` INT NOT NULL,
  `BANK_NAME` VARCHAR(45) NULL,
  `BANK_LOCATION` VARCHAR(45) NULL,
  `BANK_INFO` VARCHAR(45) NULL,
  `Hospital_H_ID` INT NOT NULL,
  PRIMARY KEY (`BANK_ID`),
  -- INDEX `fk_Blood Bank_Hospital1_idx` (`Hospital_H_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Blood Bank_Hospital1`
    FOREIGN KEY (`Hospital_H_ID`)
    REFERENCES `mydb`.`Hospital` (`H_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
